SERVICE_VAR: "www"

#SERVICES: "{{ SERVICE_DETAILS | map('combine', SERVICE_DEFAULTS) | list }}"
service_list: []
SERVICES: "{% for svc in SERVICE_DETAILS %}{{ service_list.append(SERVICE_DEFAULTS | combine(svc)) }}{% endfor %}{{ service_list }}"

SERVICE_DEFAULTS:
  remark: blah

SERVICE_DETAILS:
  - name: test1
    port: 80
    remark: fail
  - name: test2
    port: 443
